// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package main

import (
	"fmt"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type tableViewType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("information_schema").
func (v *tableViewType) Schema() string { _ = "STUB: not implemented"; return "" }

// Name returns a view or table name in SQL database ("tables").
func (v *tableViewType) Name() string {
	_ = "STUB: not implemented"

	// Columns returns a new slice of column names for that view or table in SQL database.
	return ""
}

func (v *tableViewType) Columns() []string { _ = "STUB: not implemented"; return nil }

// NewStruct makes a new struct for that view or table.
func (v *tableViewType) NewStruct() reform.Struct {
	_ = "STUB: not implemented"

	// tableView represents tables view or table in SQL database.
	return *new(reform.Struct)
}

var tableView = &tableViewType{
	s: parse.StructInfo{
		Type:      "table",
		SQLSchema: "information_schema",
		SQLName:   "tables",
		Fields: []parse.FieldInfo{
			{Name: "TableCatalog", Type: "string", Column: "table_catalog"},
			{Name: "TableSchema", Type: "string", Column: "table_schema"},
			{Name: "TableName", Type: "string", Column: "table_name"},
			{Name: "TableType", Type: "string", Column: "table_type"},
		},
		PKFieldIndex: -1,
	},
	z: new(table).Values(),
}

// String returns a string representation of this struct or record.
func (s table) String() string { _ = "STUB: not implemented"; return "" }

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *table) Values() []interface{} { _ = "STUB: not implemented"; return nil }

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *table) Pointers() []interface{} { _ = "STUB: not implemented"; return nil }

// View returns View object for that struct.
func (s *table) View() reform.View {
	_ = "STUB: not implemented"

	// check interfaces
	return *new(reform.View)
}

var (
	_ reform.View   = tableView
	_ reform.Struct = (*table)(nil)
	_ fmt.Stringer  = (*table)(nil)
)

type columnViewType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("information_schema").
func (v *columnViewType) Schema() string { _ = "STUB: not implemented"; return "" }

// Name returns a view or table name in SQL database ("columns").
func (v *columnViewType) Name() string {
	_ = "STUB: not implemented"

	// Columns returns a new slice of column names for that view or table in SQL database.
	return ""
}

func (v *columnViewType) Columns() []string { _ = "STUB: not implemented"; return nil }

// NewStruct makes a new struct for that view or table.
func (v *columnViewType) NewStruct() reform.Struct {
	_ = "STUB: not implemented"
	return *

	// columnView represents columns view or table in SQL database.
	new(reform.Struct)
}

var columnView = &columnViewType{
	s: parse.StructInfo{
		Type:      "column",
		SQLSchema: "information_schema",
		SQLName:   "columns",
		Fields: []parse.FieldInfo{
			{Name: "TableCatalog", Type: "string", Column: "table_catalog"},
			{Name: "TableSchema", Type: "string", Column: "table_schema"},
			{Name: "TableName", Type: "string", Column: "table_name"},
			{Name: "Name", Type: "string", Column: "column_name"},
			{Name: "IsNullable", Type: "yesNo", Column: "is_nullable"},
			{Name: "Type", Type: "string", Column: "data_type"},
		},
		PKFieldIndex: -1,
	},
	z: new(column).Values(),
}

// String returns a string representation of this struct or record.
func (s column) String() string { _ = "STUB: not implemented"; return "" }

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *column) Values() []interface{} { _ = "STUB: not implemented"; return nil }

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *column) Pointers() []interface{} { _ = "STUB: not implemented"; return nil }

// View returns View object for that struct.
func (s *column) View() reform.View {
	_ = "STUB: not implemented"

	// check interfaces
	return *new(reform.View)
}

var (
	_ reform.View   = columnView
	_ reform.Struct = (*column)(nil)
	_ fmt.Stringer  = (*column)(nil)
)

type keyColumnUsageViewType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("information_schema").
func (v *keyColumnUsageViewType) Schema() string { _ = "STUB: not implemented"; return "" }

// Name returns a view or table name in SQL database ("key_column_usage").
func (v *keyColumnUsageViewType) Name() string {
	_ = "STUB: not implemented"

	// Columns returns a new slice of column names for that view or table in SQL database.
	return ""
}

func (v *keyColumnUsageViewType) Columns() []string { _ = "STUB: not implemented"; return nil }

// NewStruct makes a new struct for that view or table.
func (v *keyColumnUsageViewType) NewStruct() reform.Struct {
	_ = "STUB: not implemented"
	return *new(reform.Struct)
}

// keyColumnUsageView represents key_column_usage view or table in SQL database.
var keyColumnUsageView = &keyColumnUsageViewType{
	s: parse.StructInfo{
		Type:      "keyColumnUsage",
		SQLSchema: "information_schema",
		SQLName:   "key_column_usage",
		Fields: []parse.FieldInfo{
			{Name: "ColumnName", Type: "string", Column: "column_name"},
			{Name: "OrdinalPosition", Type: "int", Column: "ordinal_position"},
		},
		PKFieldIndex: -1,
	},
	z: new(keyColumnUsage).Values(),
}

// String returns a string representation of this struct or record.
func (s keyColumnUsage) String() string { _ = "STUB: not implemented"; return "" }

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *keyColumnUsage) Values() []interface{} { _ = "STUB: not implemented"; return nil }

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *keyColumnUsage) Pointers() []interface{} { _ = "STUB: not implemented"; return nil }

// View returns View object for that struct.
func (s *keyColumnUsage) View() reform.View {
	_ = "STUB: not implemented"
	return *

	// check interfaces
	new(reform.View)
}

var (
	_ reform.View   = keyColumnUsageView
	_ reform.Struct = (*keyColumnUsage)(nil)
	_ fmt.Stringer  = (*keyColumnUsage)(nil)
)

type sqliteMasterViewType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *sqliteMasterViewType) Schema() string { _ = "STUB: not implemented"; return "" }

// Name returns a view or table name in SQL database ("sqlite_master").
func (v *sqliteMasterViewType) Name() string {
	_ = "STUB: not implemented"

	// Columns returns a new slice of column names for that view or table in SQL database.
	return ""
}

func (v *sqliteMasterViewType) Columns() []string { _ = "STUB: not implemented"; return nil }

// NewStruct makes a new struct for that view or table.
func (v *sqliteMasterViewType) NewStruct() reform.Struct {
	_ = "STUB: not implemented"
	return *

	// sqliteMasterView represents sqlite_master view or table in SQL database.
	new(reform.Struct)
}

var sqliteMasterView = &sqliteMasterViewType{
	s: parse.StructInfo{
		Type:    "sqliteMaster",
		SQLName: "sqlite_master",
		Fields: []parse.FieldInfo{
			{Name: "Name", Type: "string", Column: "name"},
		},
		PKFieldIndex: -1,
	},
	z: new(sqliteMaster).Values(),
}

// String returns a string representation of this struct or record.
func (s sqliteMaster) String() string { _ = "STUB: not implemented"; return "" }

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *sqliteMaster) Values() []interface{} { _ = "STUB: not implemented"; return nil }

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *sqliteMaster) Pointers() []interface{} { _ = "STUB: not implemented"; return nil }

// View returns View object for that struct.
func (s *sqliteMaster) View() reform.View {
	_ = "STUB: not implemented"
	return *

	// check interfaces
	new(reform.View)
}

var (
	_ reform.View   = sqliteMasterView
	_ reform.Struct = (*sqliteMaster)(nil)
	_ fmt.Stringer  = (*sqliteMaster)(nil)
)

type sqliteTableInfoViewType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *sqliteTableInfoViewType) Schema() string { _ = "STUB: not implemented"; return "" }

// Name returns a view or table name in SQL database ("dummy").
func (v *sqliteTableInfoViewType) Name() string {
	_ = "STUB: not implemented"

	// Columns returns a new slice of column names for that view or table in SQL database.
	return ""
}

func (v *sqliteTableInfoViewType) Columns() []string { _ = "STUB: not implemented"; return nil }

// NewStruct makes a new struct for that view or table.
func (v *sqliteTableInfoViewType) NewStruct() reform.Struct {
	_ = "STUB: not implemented"
	return *new(reform.Struct)
}

// sqliteTableInfoView represents dummy view or table in SQL database.
var sqliteTableInfoView = &sqliteTableInfoViewType{
	s: parse.StructInfo{
		Type:    "sqliteTableInfo",
		SQLName: "dummy",
		Fields: []parse.FieldInfo{
			{Name: "CID", Type: "int", Column: "cid"},
			{Name: "Name", Type: "string", Column: "name"},
			{Name: "Type", Type: "string", Column: "type"},
			{Name: "NotNull", Type: "bool", Column: "notnull"},
			{Name: "DefaultValue", Type: "*string", Column: "dflt_value"},
			{Name: "PK", Type: "int", Column: "pk"},
		},
		PKFieldIndex: -1,
	},
	z: new(sqliteTableInfo).Values(),
}

// String returns a string representation of this struct or record.
func (s sqliteTableInfo) String() string { _ = "STUB: not implemented"; return "" }

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *sqliteTableInfo) Values() []interface{} { _ = "STUB: not implemented"; return nil }

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *sqliteTableInfo) Pointers() []interface{} { _ = "STUB: not implemented"; return nil }

// View returns View object for that struct.
func (s *sqliteTableInfo) View() reform.View { _ = "STUB: not implemented"; return *new(reform.View) }

// check interfaces
var (
	_ reform.View   = sqliteTableInfoView
	_ reform.Struct = (*sqliteTableInfo)(nil)
	_ fmt.Stringer  = (*sqliteTableInfo)(nil)
)

func init() {
	parse.AssertUpToDate(&tableView.s, new(table))
	parse.AssertUpToDate(&columnView.s, new(column))
	parse.AssertUpToDate(&keyColumnUsageView.s, new(keyColumnUsage))
	parse.AssertUpToDate(&sqliteMasterView.s, new(sqliteMaster))
	parse.AssertUpToDate(&sqliteTableInfoView.s, new(sqliteTableInfo))
}
