// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package models

import (
	"fmt"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type extraTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *extraTableType) Schema() string { _ = "STUB: not implemented"; return "" }

// Name returns a view or table name in SQL database ("extra").
func (v *extraTableType) Name() string {
	_ = "STUB: not implemented"

	// Columns returns a new slice of column names for that view or table in SQL database.
	return ""
}

func (v *extraTableType) Columns() []string { _ = "STUB: not implemented"; return nil }

// NewStruct makes a new struct for that view or table.
func (v *extraTableType) NewStruct() reform.Struct {
	_ = "STUB: not implemented"

	// NewRecord makes a new record for that table.
	return *new(reform.Struct)
}

func (v *extraTableType) NewRecord() reform.Record {
	_ = "STUB: not implemented"

	// PKColumnIndex returns an index of primary key column for that table in SQL database.
	return *new(reform.Record)
}

func (v *extraTableType) PKColumnIndex() uint { _ = "STUB: not implemented"; return 0 }

// ExtraTable represents extra view or table in SQL database.
var ExtraTable = &extraTableType{
	s: parse.StructInfo{
		Type:    "Extra",
		SQLName: "extra",
		Fields: []parse.FieldInfo{
			{Name: "ID", Type: "Integer", Column: "id"},
			{Name: "Name", Type: "*String", Column: "name"},
			{Name: "Byte", Type: "uint8", Column: "byte"},
			{Name: "Uint8", Type: "uint8", Column: "uint8"},
			{Name: "ByteP", Type: "*uint8", Column: "bytep"},
			{Name: "Uint8P", Type: "*uint8", Column: "uint8p"},
			{Name: "Bytes", Type: "[]uint8", Column: "bytes"},
			{Name: "Uint8s", Type: "[]uint8", Column: "uint8s"},
			{Name: "BytesA", Type: "[512]uint8", Column: "bytesa"},
			{Name: "Uint8sA", Type: "[512]uint8", Column: "uint8sa"},
			{Name: "BytesT", Type: "Bytes", Column: "bytest"},
			{Name: "Uint8sT", Type: "Uint8s", Column: "uint8st"},
		},
		PKFieldIndex: 0,
	},
	z: new(Extra).Values(),
}

// String returns a string representation of this struct or record.
func (s Extra) String() string { _ = "STUB: not implemented"; return "" }

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *Extra) Values() []interface{} { _ = "STUB: not implemented"; return nil }

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *Extra) Pointers() []interface{} { _ = "STUB: not implemented"; return nil }

// View returns View object for that struct.
func (s *Extra) View() reform.View {
	_ = "STUB: not implemented"

	// Table returns Table object for that record.
	return *new(reform.View)
}

func (s *Extra) Table() reform.Table {
	_ = "STUB: not implemented"

	// PKValue returns a value of primary key for that record.
	// Returned interface{} value is never untyped nil.
	return *new(reform.Table)
}

func (s *Extra) PKValue() interface{} {
	_ = "STUB: not implemented"

	// PKPointer returns a pointer to primary key field for that record.
	// Returned interface{} value is never untyped nil.
	return nil
}

func (s *Extra) PKPointer() interface{} {
	_ = "STUB: not implemented"

	// HasPK returns true if record has non-zero primary key set, false otherwise.
	return nil
}

func (s *Extra) HasPK() bool { _ = "STUB: not implemented"; return false }

// SetPK sets record primary key, if possible.
//
// Deprecated: prefer direct field assignment where possible: s.ID = pk.
func (s *Extra) SetPK(pk interface{}) { _ = "STUB: not implemented"; return }

// check interfaces
var (
	_ reform.View   = ExtraTable
	_ reform.Struct = (*Extra)(nil)
	_ reform.Table  = ExtraTable
	_ reform.Record = (*Extra)(nil)
	_ fmt.Stringer  = (*Extra)(nil)
)

type notExportedTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *notExportedTableType) Schema() string { _ = "STUB: not implemented"; return "" }

// Name returns a view or table name in SQL database ("not_exported").
func (v *notExportedTableType) Name() string {
	_ = "STUB: not implemented"

	// Columns returns a new slice of column names for that view or table in SQL database.
	return ""
}

func (v *notExportedTableType) Columns() []string { _ = "STUB: not implemented"; return nil }

// NewStruct makes a new struct for that view or table.
func (v *notExportedTableType) NewStruct() reform.Struct {
	_ = "STUB: not implemented"
	return *

	// NewRecord makes a new record for that table.
	new(reform.Struct)
}

func (v *notExportedTableType) NewRecord() reform.Record {
	_ = "STUB: not implemented"
	return *

	// PKColumnIndex returns an index of primary key column for that table in SQL database.
	new(reform.Record)
}

func (v *notExportedTableType) PKColumnIndex() uint { _ = "STUB: not implemented"; return 0 }

// notExportedTable represents not_exported view or table in SQL database.
var notExportedTable = &notExportedTableType{
	s: parse.StructInfo{
		Type:    "notExported",
		SQLName: "not_exported",
		Fields: []parse.FieldInfo{
			{Name: "ID", Type: "string", Column: "id"},
		},
		PKFieldIndex: 0,
	},
	z: new(notExported).Values(),
}

// String returns a string representation of this struct or record.
func (s notExported) String() string { _ = "STUB: not implemented"; return "" }

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *notExported) Values() []interface{} { _ = "STUB: not implemented"; return nil }

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *notExported) Pointers() []interface{} { _ = "STUB: not implemented"; return nil }

// View returns View object for that struct.
func (s *notExported) View() reform.View {
	_ = "STUB: not implemented"
	return *

	// Table returns Table object for that record.
	new(reform.View)
}

func (s *notExported) Table() reform.Table {
	_ = "STUB: not implemented"
	return *

	// PKValue returns a value of primary key for that record.
	// Returned interface{} value is never untyped nil.
	new(reform.Table)
}

func (s *notExported) PKValue() interface{} {
	_ = "STUB: not implemented"

	// PKPointer returns a pointer to primary key field for that record.
	// Returned interface{} value is never untyped nil.
	return nil
}

func (s *notExported) PKPointer() interface{} {
	_ = "STUB: not implemented"

	// HasPK returns true if record has non-zero primary key set, false otherwise.
	return nil
}

func (s *notExported) HasPK() bool { _ = "STUB: not implemented"; return false }

// SetPK sets record primary key, if possible.
//
// Deprecated: prefer direct field assignment where possible: s.ID = pk.
func (s *notExported) SetPK(pk interface{}) { _ = "STUB: not implemented"; return }

// check interfaces
var (
	_ reform.View   = notExportedTable
	_ reform.Struct = (*notExported)(nil)
	_ reform.Table  = notExportedTable
	_ reform.Record = (*notExported)(nil)
	_ fmt.Stringer  = (*notExported)(nil)
)

func init() {
	parse.AssertUpToDate(&ExtraTable.s, new(Extra))
	parse.AssertUpToDate(&notExportedTable.s, new(notExported))
}
