// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package models

import (
	"fmt"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type personTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *personTableType) Schema() string { _ = "STUB: not implemented"; return "" }

// Name returns a view or table name in SQL database ("people").
func (v *personTableType) Name() string {
	_ = "STUB: not implemented"

	// Columns returns a new slice of column names for that view or table in SQL database.
	return ""
}

func (v *personTableType) Columns() []string { _ = "STUB: not implemented"; return nil }

// NewStruct makes a new struct for that view or table.
func (v *personTableType) NewStruct() reform.Struct {
	_ = "STUB: not implemented"
	return *

	// NewRecord makes a new record for that table.
	new(reform.Struct)
}

func (v *personTableType) NewRecord() reform.Record {
	_ = "STUB: not implemented"
	return *

	// PKColumnIndex returns an index of primary key column for that table in SQL database.
	new(reform.Record)
}

func (v *personTableType) PKColumnIndex() uint { _ = "STUB: not implemented"; return 0 }

// PersonTable represents people view or table in SQL database.
var PersonTable = &personTableType{
	s: parse.StructInfo{
		Type:    "Person",
		SQLName: "people",
		Fields: []parse.FieldInfo{
			{Name: "ID", Type: "int32", Column: "id"},
			{Name: "GroupID", Type: "*int32", Column: "group_id"},
			{Name: "Name", Type: "string", Column: "name"},
			{Name: "Email", Type: "*string", Column: "email"},
			{Name: "CreatedAt", Type: "time.Time", Column: "created_at"},
			{Name: "UpdatedAt", Type: "*time.Time", Column: "updated_at"},
		},
		PKFieldIndex: 0,
	},
	z: new(Person).Values(),
}

// String returns a string representation of this struct or record.
func (s Person) String() string { _ = "STUB: not implemented"; return "" }

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *Person) Values() []interface{} { _ = "STUB: not implemented"; return nil }

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *Person) Pointers() []interface{} { _ = "STUB: not implemented"; return nil }

// View returns View object for that struct.
func (s *Person) View() reform.View {
	_ = "STUB: not implemented"

	// Table returns Table object for that record.
	return *new(reform.View)
}

func (s *Person) Table() reform.Table {
	_ = "STUB: not implemented"

	// PKValue returns a value of primary key for that record.
	// Returned interface{} value is never untyped nil.
	return *new(reform.Table)
}

func (s *Person) PKValue() interface{} {
	_ = "STUB: not implemented"

	// PKPointer returns a pointer to primary key field for that record.
	// Returned interface{} value is never untyped nil.
	return nil
}

func (s *Person) PKPointer() interface{} {
	_ = "STUB: not implemented"

	// HasPK returns true if record has non-zero primary key set, false otherwise.
	return nil
}

func (s *Person) HasPK() bool { _ = "STUB: not implemented"; return false }

// SetPK sets record primary key, if possible.
//
// Deprecated: prefer direct field assignment where possible: s.ID = pk.
func (s *Person) SetPK(pk interface{}) { _ = "STUB: not implemented"; return }

// check interfaces
var (
	_ reform.View   = PersonTable
	_ reform.Struct = (*Person)(nil)
	_ reform.Table  = PersonTable
	_ reform.Record = (*Person)(nil)
	_ fmt.Stringer  = (*Person)(nil)
)

type projectTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *projectTableType) Schema() string { _ = "STUB: not implemented"; return "" }

// Name returns a view or table name in SQL database ("projects").
func (v *projectTableType) Name() string {
	_ = "STUB: not implemented"

	// Columns returns a new slice of column names for that view or table in SQL database.
	return ""
}

func (v *projectTableType) Columns() []string { _ = "STUB: not implemented"; return nil }

// NewStruct makes a new struct for that view or table.
func (v *projectTableType) NewStruct() reform.Struct {
	_ = "STUB: not implemented"
	return *

	// NewRecord makes a new record for that table.
	new(reform.Struct)
}

func (v *projectTableType) NewRecord() reform.Record {
	_ = "STUB: not implemented"
	return *

	// PKColumnIndex returns an index of primary key column for that table in SQL database.
	new(reform.Record)
}

func (v *projectTableType) PKColumnIndex() uint { _ = "STUB: not implemented"; return 0 }

// ProjectTable represents projects view or table in SQL database.
var ProjectTable = &projectTableType{
	s: parse.StructInfo{
		Type:    "Project",
		SQLName: "projects",
		Fields: []parse.FieldInfo{
			{Name: "Name", Type: "string", Column: "name"},
			{Name: "ID", Type: "string", Column: "id"},
			{Name: "Start", Type: "time.Time", Column: "start"},
			{Name: "End", Type: "*time.Time", Column: "end"},
		},
		PKFieldIndex: 1,
	},
	z: new(Project).Values(),
}

// String returns a string representation of this struct or record.
func (s Project) String() string { _ = "STUB: not implemented"; return "" }

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *Project) Values() []interface{} { _ = "STUB: not implemented"; return nil }

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *Project) Pointers() []interface{} { _ = "STUB: not implemented"; return nil }

// View returns View object for that struct.
func (s *Project) View() reform.View {
	_ = "STUB: not implemented"
	return *

	// Table returns Table object for that record.
	new(reform.View)
}

func (s *Project) Table() reform.Table {
	_ = "STUB: not implemented"
	return *

	// PKValue returns a value of primary key for that record.
	// Returned interface{} value is never untyped nil.
	new(reform.Table)
}

func (s *Project) PKValue() interface{} {
	_ = "STUB: not implemented"

	// PKPointer returns a pointer to primary key field for that record.
	// Returned interface{} value is never untyped nil.
	return nil
}

func (s *Project) PKPointer() interface{} {
	_ = "STUB: not implemented"

	// HasPK returns true if record has non-zero primary key set, false otherwise.
	return nil
}

func (s *Project) HasPK() bool { _ = "STUB: not implemented"; return false }

// SetPK sets record primary key, if possible.
//
// Deprecated: prefer direct field assignment where possible: s.ID = pk.
func (s *Project) SetPK(pk interface{}) { _ = "STUB: not implemented"; return }

// check interfaces
var (
	_ reform.View   = ProjectTable
	_ reform.Struct = (*Project)(nil)
	_ reform.Table  = ProjectTable
	_ reform.Record = (*Project)(nil)
	_ fmt.Stringer  = (*Project)(nil)
)

type personProjectViewType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *personProjectViewType) Schema() string { _ = "STUB: not implemented"; return "" }

// Name returns a view or table name in SQL database ("person_project").
func (v *personProjectViewType) Name() string {
	_ = "STUB: not implemented"

	// Columns returns a new slice of column names for that view or table in SQL database.
	return ""
}

func (v *personProjectViewType) Columns() []string { _ = "STUB: not implemented"; return nil }

// NewStruct makes a new struct for that view or table.
func (v *personProjectViewType) NewStruct() reform.Struct {
	_ = "STUB: not implemented"
	return *new(reform.Struct)
}

// PersonProjectView represents person_project view or table in SQL database.
var PersonProjectView = &personProjectViewType{
	s: parse.StructInfo{
		Type:    "PersonProject",
		SQLName: "person_project",
		Fields: []parse.FieldInfo{
			{Name: "PersonID", Type: "int32", Column: "person_id"},
			{Name: "ProjectID", Type: "string", Column: "project_id"},
		},
		PKFieldIndex: -1,
	},
	z: new(PersonProject).Values(),
}

// String returns a string representation of this struct or record.
func (s PersonProject) String() string { _ = "STUB: not implemented"; return "" }

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *PersonProject) Values() []interface{} { _ = "STUB: not implemented"; return nil }

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *PersonProject) Pointers() []interface{} { _ = "STUB: not implemented"; return nil }

// View returns View object for that struct.
func (s *PersonProject) View() reform.View {
	_ = "STUB: not implemented"
	return *

	// check interfaces
	new(reform.View)
}

var (
	_ reform.View   = PersonProjectView
	_ reform.Struct = (*PersonProject)(nil)
	_ fmt.Stringer  = (*PersonProject)(nil)
)

type iDOnlyTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *iDOnlyTableType) Schema() string { _ = "STUB: not implemented"; return "" }

// Name returns a view or table name in SQL database ("id_only").
func (v *iDOnlyTableType) Name() string {
	_ = "STUB: not implemented"

	// Columns returns a new slice of column names for that view or table in SQL database.
	return ""
}

func (v *iDOnlyTableType) Columns() []string { _ = "STUB: not implemented"; return nil }

// NewStruct makes a new struct for that view or table.
func (v *iDOnlyTableType) NewStruct() reform.Struct {
	_ = "STUB: not implemented"
	return *

	// NewRecord makes a new record for that table.
	new(reform.Struct)
}

func (v *iDOnlyTableType) NewRecord() reform.Record {
	_ = "STUB: not implemented"
	return *

	// PKColumnIndex returns an index of primary key column for that table in SQL database.
	new(reform.Record)
}

func (v *iDOnlyTableType) PKColumnIndex() uint { _ = "STUB: not implemented"; return 0 }

// IDOnlyTable represents id_only view or table in SQL database.
var IDOnlyTable = &iDOnlyTableType{
	s: parse.StructInfo{
		Type:    "IDOnly",
		SQLName: "id_only",
		Fields: []parse.FieldInfo{
			{Name: "ID", Type: "int32", Column: "id"},
		},
		PKFieldIndex: 0,
	},
	z: new(IDOnly).Values(),
}

// String returns a string representation of this struct or record.
func (s IDOnly) String() string { _ = "STUB: not implemented"; return "" }

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *IDOnly) Values() []interface{} { _ = "STUB: not implemented"; return nil }

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *IDOnly) Pointers() []interface{} { _ = "STUB: not implemented"; return nil }

// View returns View object for that struct.
func (s *IDOnly) View() reform.View {
	_ = "STUB: not implemented"

	// Table returns Table object for that record.
	return *new(reform.View)
}

func (s *IDOnly) Table() reform.Table {
	_ = "STUB: not implemented"

	// PKValue returns a value of primary key for that record.
	// Returned interface{} value is never untyped nil.
	return *new(reform.Table)
}

func (s *IDOnly) PKValue() interface{} {
	_ = "STUB: not implemented"

	// PKPointer returns a pointer to primary key field for that record.
	// Returned interface{} value is never untyped nil.
	return nil
}

func (s *IDOnly) PKPointer() interface{} {
	_ = "STUB: not implemented"

	// HasPK returns true if record has non-zero primary key set, false otherwise.
	return nil
}

func (s *IDOnly) HasPK() bool { _ = "STUB: not implemented"; return false }

// SetPK sets record primary key, if possible.
//
// Deprecated: prefer direct field assignment where possible: s.ID = pk.
func (s *IDOnly) SetPK(pk interface{}) { _ = "STUB: not implemented"; return }

// check interfaces
var (
	_ reform.View   = IDOnlyTable
	_ reform.Struct = (*IDOnly)(nil)
	_ reform.Table  = IDOnlyTable
	_ reform.Record = (*IDOnly)(nil)
	_ fmt.Stringer  = (*IDOnly)(nil)
)

type constraintsTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *constraintsTableType) Schema() string { _ = "STUB: not implemented"; return "" }

// Name returns a view or table name in SQL database ("constraints").
func (v *constraintsTableType) Name() string {
	_ = "STUB: not implemented"

	// Columns returns a new slice of column names for that view or table in SQL database.
	return ""
}

func (v *constraintsTableType) Columns() []string { _ = "STUB: not implemented"; return nil }

// NewStruct makes a new struct for that view or table.
func (v *constraintsTableType) NewStruct() reform.Struct {
	_ = "STUB: not implemented"
	return *

	// NewRecord makes a new record for that table.
	new(reform.Struct)
}

func (v *constraintsTableType) NewRecord() reform.Record {
	_ = "STUB: not implemented"
	return *

	// PKColumnIndex returns an index of primary key column for that table in SQL database.
	new(reform.Record)
}

func (v *constraintsTableType) PKColumnIndex() uint { _ = "STUB: not implemented"; return 0 }

// ConstraintsTable represents constraints view or table in SQL database.
var ConstraintsTable = &constraintsTableType{
	s: parse.StructInfo{
		Type:    "Constraints",
		SQLName: "constraints",
		Fields: []parse.FieldInfo{
			{Name: "I", Type: "int32", Column: "i"},
			{Name: "ID", Type: "string", Column: "id"},
		},
		PKFieldIndex: 1,
	},
	z: new(Constraints).Values(),
}

// String returns a string representation of this struct or record.
func (s Constraints) String() string { _ = "STUB: not implemented"; return "" }

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *Constraints) Values() []interface{} { _ = "STUB: not implemented"; return nil }

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *Constraints) Pointers() []interface{} { _ = "STUB: not implemented"; return nil }

// View returns View object for that struct.
func (s *Constraints) View() reform.View {
	_ = "STUB: not implemented"
	return *

	// Table returns Table object for that record.
	new(reform.View)
}

func (s *Constraints) Table() reform.Table {
	_ = "STUB: not implemented"
	return *

	// PKValue returns a value of primary key for that record.
	// Returned interface{} value is never untyped nil.
	new(reform.Table)
}

func (s *Constraints) PKValue() interface{} {
	_ = "STUB: not implemented"

	// PKPointer returns a pointer to primary key field for that record.
	// Returned interface{} value is never untyped nil.
	return nil
}

func (s *Constraints) PKPointer() interface{} {
	_ = "STUB: not implemented"

	// HasPK returns true if record has non-zero primary key set, false otherwise.
	return nil
}

func (s *Constraints) HasPK() bool { _ = "STUB: not implemented"; return false }

// SetPK sets record primary key, if possible.
//
// Deprecated: prefer direct field assignment where possible: s.ID = pk.
func (s *Constraints) SetPK(pk interface{}) { _ = "STUB: not implemented"; return }

// check interfaces
var (
	_ reform.View   = ConstraintsTable
	_ reform.Struct = (*Constraints)(nil)
	_ reform.Table  = ConstraintsTable
	_ reform.Record = (*Constraints)(nil)
	_ fmt.Stringer  = (*Constraints)(nil)
)

type compositePkViewType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *compositePkViewType) Schema() string { _ = "STUB: not implemented"; return "" }

// Name returns a view or table name in SQL database ("composite_pk").
func (v *compositePkViewType) Name() string {
	_ = "STUB: not implemented"

	// Columns returns a new slice of column names for that view or table in SQL database.
	return ""
}

func (v *compositePkViewType) Columns() []string { _ = "STUB: not implemented"; return nil }

// NewStruct makes a new struct for that view or table.
func (v *compositePkViewType) NewStruct() reform.Struct {
	_ = "STUB: not implemented"
	return *

	// CompositePkView represents composite_pk view or table in SQL database.
	new(reform.Struct)
}

var CompositePkView = &compositePkViewType{
	s: parse.StructInfo{
		Type:    "CompositePk",
		SQLName: "composite_pk",
		Fields: []parse.FieldInfo{
			{Name: "I", Type: "int32", Column: "i"},
			{Name: "Name", Type: "string", Column: "name"},
			{Name: "J", Type: "string", Column: "j"},
		},
		PKFieldIndex: -1,
	},
	z: new(CompositePk).Values(),
}

// String returns a string representation of this struct or record.
func (s CompositePk) String() string { _ = "STUB: not implemented"; return "" }

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *CompositePk) Values() []interface{} { _ = "STUB: not implemented"; return nil }

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *CompositePk) Pointers() []interface{} { _ = "STUB: not implemented"; return nil }

// View returns View object for that struct.
func (s *CompositePk) View() reform.View {
	_ = "STUB: not implemented"
	return *

	// check interfaces
	new(reform.View)
}

var (
	_ reform.View   = CompositePkView
	_ reform.Struct = (*CompositePk)(nil)
	_ fmt.Stringer  = (*CompositePk)(nil)
)

type legacyPersonTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("legacy").
func (v *legacyPersonTableType) Schema() string { _ = "STUB: not implemented"; return "" }

// Name returns a view or table name in SQL database ("people").
func (v *legacyPersonTableType) Name() string {
	_ = "STUB: not implemented"

	// Columns returns a new slice of column names for that view or table in SQL database.
	return ""
}

func (v *legacyPersonTableType) Columns() []string { _ = "STUB: not implemented"; return nil }

// NewStruct makes a new struct for that view or table.
func (v *legacyPersonTableType) NewStruct() reform.Struct {
	_ = "STUB: not implemented"
	return *

	// NewRecord makes a new record for that table.
	new(reform.Struct)
}

func (v *legacyPersonTableType) NewRecord() reform.Record {
	_ = "STUB: not implemented"
	return *

	// PKColumnIndex returns an index of primary key column for that table in SQL database.
	new(reform.Record)
}

func (v *legacyPersonTableType) PKColumnIndex() uint { _ = "STUB: not implemented"; return 0 }

// LegacyPersonTable represents people view or table in SQL database.
var LegacyPersonTable = &legacyPersonTableType{
	s: parse.StructInfo{
		Type:      "LegacyPerson",
		SQLSchema: "legacy",
		SQLName:   "people",
		Fields: []parse.FieldInfo{
			{Name: "ID", Type: "int32", Column: "id"},
			{Name: "Name", Type: "*string", Column: "name"},
		},
		PKFieldIndex: 0,
	},
	z: new(LegacyPerson).Values(),
}

// String returns a string representation of this struct or record.
func (s LegacyPerson) String() string { _ = "STUB: not implemented"; return "" }

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *LegacyPerson) Values() []interface{} { _ = "STUB: not implemented"; return nil }

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *LegacyPerson) Pointers() []interface{} { _ = "STUB: not implemented"; return nil }

// View returns View object for that struct.
func (s *LegacyPerson) View() reform.View {
	_ = "STUB: not implemented"
	return *

	// Table returns Table object for that record.
	new(reform.View)
}

func (s *LegacyPerson) Table() reform.Table {
	_ = "STUB: not implemented"
	return *

	// PKValue returns a value of primary key for that record.
	// Returned interface{} value is never untyped nil.
	new(reform.Table)
}

func (s *LegacyPerson) PKValue() interface{} {
	_ = "STUB: not implemented"

	// PKPointer returns a pointer to primary key field for that record.
	// Returned interface{} value is never untyped nil.
	return nil
}

func (s *LegacyPerson) PKPointer() interface{} {
	_ = "STUB: not implemented"

	// HasPK returns true if record has non-zero primary key set, false otherwise.
	return nil
}

func (s *LegacyPerson) HasPK() bool { _ = "STUB: not implemented"; return false }

// SetPK sets record primary key, if possible.
//
// Deprecated: prefer direct field assignment where possible: s.ID = pk.
func (s *LegacyPerson) SetPK(pk interface{}) { _ = "STUB: not implemented"; return }

// check interfaces
var (
	_ reform.View   = LegacyPersonTable
	_ reform.Struct = (*LegacyPerson)(nil)
	_ reform.Table  = LegacyPersonTable
	_ reform.Record = (*LegacyPerson)(nil)
	_ fmt.Stringer  = (*LegacyPerson)(nil)
)

func init() {
	parse.AssertUpToDate(&PersonTable.s, new(Person))
	parse.AssertUpToDate(&ProjectTable.s, new(Project))
	parse.AssertUpToDate(&PersonProjectView.s, new(PersonProject))
	parse.AssertUpToDate(&IDOnlyTable.s, new(IDOnly))
	parse.AssertUpToDate(&ConstraintsTable.s, new(Constraints))
	parse.AssertUpToDate(&CompositePkView.s, new(CompositePk))
	parse.AssertUpToDate(&LegacyPersonTable.s, new(LegacyPerson))
}
